python3 examples/gemma/run_gemma_flax.py\
     --output_dir ./output \
     --config_name google/gemma-1.1-2b-it \
     --dataset_name /fs-computility/llm/caizheng/alpa_data/data/sg_90k_part1.json \
     --do_train \
     --block_size 1024 \
     --per_device_train_batch_size 4 \
     --per_device_eval_batch_size 1 \
     --num_micro_batches 4 \
     --dtype float32 \
     --learning_rate 5e-4 \
     --weight_decay 0.0 \
     --overwrite_output_dir \
     --num_train_epochs 3 \
     --logging_steps 1 \
     --save_steps 3000 \
     --eval_steps 1000 \
     --use_data_sample \
     --pipeline_parallel 2 \
     --parallel_strategy parallel_3d